In [9]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences

In [10]:
from tensorflow.keras.preprocessing.text import one_hot

In [11]:
import numpy as np

In [12]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [13]:
voc_size=10000

In [14]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]#ignore
one_hot_repr

[[3833, 5955, 1646, 8226],
 [3833, 5955, 1646, 3699],
 [3833, 4222, 1646, 1695],
 [3406, 5372, 1789, 91, 9541],
 [3406, 5372, 1789, 91, 1252],
 [107, 3833, 1066, 1646, 9570],
 [99, 791, 2973, 91]]

In [16]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3833 5955 1646 8226]
 [   0    0    0    0 3833 5955 1646 3699]
 [   0    0    0    0 3833 4222 1646 1695]
 [   0    0    0 3406 5372 1789   91 9541]
 [   0    0    0 3406 5372 1789   91 1252]
 [   0    0    0  107 3833 1066 1646 9570]
 [   0    0    0    0   99  791 2973   91]]


In [17]:
## Feature Representation
dim=10

In [18]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\python\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
embedded_docs[0]

array([   0,    0,    0,    0, 3833, 5955, 1646, 8226])

In [23]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step


array([[ 5.73093817e-03, -2.03479454e-03, -1.53529271e-02,
        -4.95881326e-02,  4.77400459e-02,  3.74174155e-02,
         2.68641822e-02, -4.31524776e-02,  3.23866941e-02,
         1.44969858e-02],
       [ 5.73093817e-03, -2.03479454e-03, -1.53529271e-02,
        -4.95881326e-02,  4.77400459e-02,  3.74174155e-02,
         2.68641822e-02, -4.31524776e-02,  3.23866941e-02,
         1.44969858e-02],
       [ 5.73093817e-03, -2.03479454e-03, -1.53529271e-02,
        -4.95881326e-02,  4.77400459e-02,  3.74174155e-02,
         2.68641822e-02, -4.31524776e-02,  3.23866941e-02,
         1.44969858e-02],
       [ 5.73093817e-03, -2.03479454e-03, -1.53529271e-02,
        -4.95881326e-02,  4.77400459e-02,  3.74174155e-02,
         2.68641822e-02, -4.31524776e-02,  3.23866941e-02,
         1.44969858e-02],
       [ 4.99894470e-03, -3.16913724e-02,  1.34897232e-03,
         1.25695355e-02,  1.30336918e-02, -4.27600741e-02,
        -2.40005255e-02, -2.34233867e-02,  2.07284205e-02,
         3.